// app/layout.tsx or app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Userprovider from "@/provider/Userprovider";
import ReactQueryProvider from "@/provider/ReactQueryProvider";

const interFont = Inter({
  variable: "--font-Inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={`${interFont.variable} antialiased relative`}>
          <Userprovider>{children}</Userprovider>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
