const extensionToMime: Record<string, string> = {
  ".ts": "application/typescript",
  ".js": "application/javascript",
  ".css": "text/css",
  ".less": "text/css",
  ".scss": "text/css",
  ".json": "application/json",
  ".html": "text/html",
  ".xml": "application/xml",
  ".php": "application/x-httpd-php",
  ".cs": "text/x-csharp",
  ".cpp": "text/x-c++src",
  ".razor": "text/html",
  ".md": "text/markdown",
  ".diff": "text/plain",
  ".java": "text/x-java-source",
  ".vb": "text/x-vb",
  ".coffee": "text/coffeescript",
  ".hbs": "text/x-handlebars-template",
  ".bat": "text/x-bat",
  ".pug": "text/x-pug",
  ".fs": "text/x-fsharp",
  ".lua": "text/x-lua",
  ".ps1": "text/x-powershell",
  ".py": "text/x-python",
  ".rb": "text/x-ruby",
  ".sass": "text/x-sass",
  ".r": "text/x-r",
  ".m": "text/x-objective-c",
  ".txt": "text/plain",
};
export default extensionToMime;
